let guests=[], scanner=null, busy=false, protocolToken=null, protocolName='', protocolRole='protocol', chiefTeam=[], chiefTasks=[];
const A=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(t){A('#loginMsg').textContent=t;A('#loginMsg').classList.remove('hidden')}
function toast(t){const x=document.createElement('div');x.className='reception-toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}
async function init(){try{protocolToken=sessionStorage.getItem('protocolToken');protocolName=sessionStorage.getItem('protocolName')||'';protocolRole=sessionStorage.getItem('protocolRole')||'protocol'}catch(_){} if(protocolToken){const ok=await loadGuests(true);if(ok){await enter();return}try{sessionStorage.removeItem('protocolToken');sessionStorage.removeItem('protocolName');sessionStorage.removeItem('protocolRole')}catch(_){}} const {data}=await supabaseClient.auth.getSession();if(data.session){await enter()}else A('#login').classList.remove('hidden')}
async function enter(){A('#login').classList.add('hidden');A('#reception').classList.remove('hidden');A('#chiefTools')?.classList.toggle('hidden',protocolRole!=='chief');await loadGuests();if(protocolRole==='chief')await loadChiefTools();A('#code').focus()}
async function loadGuests(protocol=!!protocolToken){const r=protocol?await supabaseClient.rpc('protocol_checkin_list',{p_token:protocolToken}):await supabaseClient.rpc('admin_list_invitations_checkin');if(r.error){if(protocol)return false;toast(r.error.message);return false}guests=r.data||[];updateCounter();return true}
function updateCounter(){let n=0,p=0;guests.forEach(g=>{if(g.checked_in){n++;p+=1+(g.companion_count||0)}});A('#countIn').textContent=n;A('#countPeople').textContent=p}
function render(g){const box=A('#result');if(!g){box.classList.add('hidden');return}const people=1+(g.companion_count||0);let state;if(g.checked_in){state=`<div class="result-already"><b>✓ Entrada já registada</b><span>${g.checked_in_at?new Date(g.checked_in_at).toLocaleString('pt-PT'):''}</span></div>`}else if(g.rsvp_status==='confirmed'){state='<div class="result-valid"><b>✓ Presença confirmada</b><span>Convite válido para a recepção.</span></div>'}else{state=`<div class="result-warning"><b>⚠ Estado: ${esc(g.rsvp_status)}</b><span>Este convidado ainda não confirmou a presença.</span></div>`}box.innerHTML=`<div class="guest-result-inner"><div class="guest-main"><p class="eyebrow">Convidado</p><h2>${esc(g.full_name)}</h2><div class="guest-meta"><span><b>${esc(g.code)}</b></span><span>${people} pessoa(s)</span><span>Permitido: ${g.allowed_guests}</span></div>${g.table_name?`<div class="assigned-table"><small>MESA</small><strong>${esc(g.table_name)}</strong><span>${g.table_capacity?`Capacidade ${g.table_capacity} lugares`:''}</span></div>`:'<div class="assigned-table no-table"><small>ASSENTO</small><strong>Mesa ainda não atribuída</strong></div>'}${state}</div><div class="guest-action">${g.checked_in?'<button class="button secondary" id="again">Próximo convidado</button>':`<button class="button reception-confirm" id="confirm">Confirmar entrada</button>`}</div></div>`;box.classList.remove('hidden');A('#again')?.addEventListener('click',next);A('#confirm')?.addEventListener('click',()=>confirmEntry(g.id));}
async function search(raw){const key=String(raw||'').trim();if(!key){toast('Introduza o código do convite.');A('#code').focus();return}const g=guests.find(x=>x.code.toLowerCase()===key.toLowerCase());if(!g){render(null);toast('Convite não encontrado.');return}render(g)}
async function confirmEntry(id){if(busy)return;const g=guests.find(x=>x.id===id);if(!g||g.checked_in)return;busy=true;const b=A('#confirm');if(b){b.disabled=true;b.textContent='A confirmar…'}const {error}=protocolToken?await supabaseClient.rpc('protocol_check_in',{p_token:protocolToken,p_invitation_id:id}):await supabaseClient.rpc('admin_check_in_invitation',{invitation_id:id});if(error){toast(error.message);busy=false;if(b){b.disabled=false;b.textContent='Confirmar entrada'}return}await loadGuests();toast(`✓ Entrada confirmada — ${g.full_name}`);render(guests.find(x=>x.id===id));setTimeout(next,1800);busy=false}
function next(){A('#result').classList.add('hidden');A('#code').value='';A('#code').focus()}
A('#protocolLoginForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await supabaseClient.rpc('verify_protocol',{p_access_code:A('#protocolAccessCode').value.trim(),p_pin:A('#protocolAccessPin').value.trim()});if(error||!data?.length){A('#protocolLoginMsg').textContent='Código ou PIN incorrecto.';A('#protocolLoginMsg').classList.remove('hidden');return}protocolToken=data[0].session_token;protocolName=data[0].full_name;protocolRole=data[0].role||'protocol';try{sessionStorage.setItem('protocolToken',protocolToken);sessionStorage.setItem('protocolName',protocolName);sessionStorage.setItem('protocolRole',protocolRole)}catch(_){}await enter()};
A('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:A('#email').value,password:A('#password').value});if(error)msg('Email ou palavra-passe incorrectos.');else await enter()};
A('#logout').onclick=async()=>{try{sessionStorage.removeItem('protocolToken');sessionStorage.removeItem('protocolName');sessionStorage.removeItem('protocolRole')}catch(_){}await supabaseClient.auth.signOut();location.reload()};A('#search').onclick=()=>search(A('#code').value);A('#code').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search(e.target.value)}});
A('#startScanner').onclick=async()=>{if(!window.Html5Qrcode){toast('Leitor QR indisponível.');return}if(scanner)return;A('#reader').classList.remove('hidden');A('#startScanner').classList.add('hidden');A('#stopScanner').classList.remove('hidden');scanner=new Html5Qrcode('reader');try{await scanner.start({facingMode:'environment'},{fps:12,qrbox:{width:260,height:260}},text=>{let code=text;try{const u=new URL(text);code=u.searchParams.get('convite')||text}catch(_){}A('#code').value=code;search(code);stopScanner()},()=>{})}catch(e){toast('Não foi possível abrir a câmara. Verifique a permissão.');stopScanner()}};
async function stopScanner(){if(scanner){try{await scanner.stop()}catch(_){}try{scanner.clear()}catch(_){}scanner=null}A('#reader').classList.add('hidden');A('#startScanner').classList.remove('hidden');A('#stopScanner').classList.add('hidden')};A('#stopScanner').onclick=stopScanner;
init();

async function loadChiefTools(){
 const [team,tasks]=await Promise.all([
   supabaseClient.rpc('chief_list_protocols',{p_token:protocolToken}),
   supabaseClient.rpc('chief_list_tasks',{p_token:protocolToken})
 ]);
 if(team.error||tasks.error){toast((team.error||tasks.error).message);return}
 chiefTeam=team.data||[];chiefTasks=tasks.data||[];renderChiefTools();
}
function renderChiefTools(){
 const list=A('#chiefTeamList'),sel=A('#chiefTaskProtocol'),tasks=A('#chiefTaskList');
 const workers=chiefTeam.filter(p=>p.role==='protocol');
 if(list)list.innerHTML=workers.map(p=>`<div class="chief-task"><div class="protocol-avatar">${esc((p.full_name||'?').slice(0,1).toUpperCase())}</div><div class="chief-task-main"><b>${esc(p.full_name)}</b><small>${esc(p.access_code)} · ${p.active?'Activo':'Inactivo'}</small></div></div>`).join('')||'<div class="empty-state">Ainda não existem protocolos.</div>';
 if(sel)sel.innerHTML=workers.map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('')||'<option value="">Sem protocolos</option>';
 if(tasks)tasks.innerHTML=chiefTasks.map(t=>`<div class="chief-task"><div class="chief-task-main"><b>${esc(t.protocol_name)} — ${esc(t.title)}</b><small>${esc(t.description||'Sem descrição')}</small></div><div class="chief-task-actions"><button class="icon-btn" onclick="chiefToggleTask(${t.id},${!t.completed})">${t.completed?'Reabrir':'Concluir'}</button><button class="icon-btn danger" onclick="chiefDeleteTask(${t.id})">Remover</button></div></div>`).join('')||'<div class="empty-state">Ainda não existem tarefas atribuídas.</div>';
}
A('#chiefTaskForm')?.addEventListener('submit',async e=>{e.preventDefault();const protocolId=A('#chiefTaskProtocol').value,title=A('#chiefTaskTitle').value.trim(),description=A('#chiefTaskDescription').value.trim();if(!protocolId||!title)return;const r=await supabaseClient.rpc('chief_create_task',{p_token:protocolToken,p_protocol_id:protocolId,p_title:title,p_description:description||null});if(r.error){toast(r.error.message);return}A('#chiefTaskForm').reset();await loadChiefTools();toast('Tarefa atribuída.')});
window.chiefToggleTask=async(id,done)=>{const r=await supabaseClient.rpc('chief_toggle_task',{p_token:protocolToken,p_task_id:id,p_completed:done});if(r.error){toast(r.error.message);return}await loadChiefTools()};
window.chiefDeleteTask=async id=>{if(!confirm('Remover esta tarefa?'))return;const r=await supabaseClient.rpc('chief_delete_task',{p_token:protocolToken,p_task_id:id});if(r.error){toast(r.error.message);return}await loadChiefTools()};
A('#chiefAddProtocol')?.addEventListener('click',async()=>{const name=prompt('Nome completo do novo protocolo:');if(!name)return;const phone=prompt('WhatsApp (opcional):')||'';const code=prompt('Código de acesso:');if(!code)return;const pin=prompt('PIN (mínimo 4 dígitos):');if(!pin)return;const r=await supabaseClient.rpc('chief_create_protocol',{p_token:protocolToken,p_full_name:name,p_whatsapp:phone,p_access_code:code,p_pin:pin});if(r.error){toast(r.error.message);return}await loadChiefTools();toast('Novo protocolo criado.')});
