let guests=[], scanner=null, busy=false;
const A=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(t){A('#loginMsg').textContent=t;A('#loginMsg').classList.remove('hidden')}
function toast(t){const x=document.createElement('div');x.className='reception-toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}
async function init(){const {data}=await supabaseClient.auth.getSession();if(data.session){await enter()}else A('#login').classList.remove('hidden')}
async function enter(){A('#login').classList.add('hidden');A('#reception').classList.remove('hidden');await loadGuests();A('#code').focus()}
async function loadGuests(){const {data,error}=await supabaseClient.rpc('admin_list_invitations_checkin');if(error){toast(error.message);return}guests=data||[];updateCounter()}
function updateCounter(){let n=0,p=0;guests.forEach(g=>{if(g.checked_in){n++;p+=1+(g.companion_count||0)}});A('#countIn').textContent=n;A('#countPeople').textContent=p}
function render(g){const box=A('#result');if(!g){box.classList.add('hidden');return}const people=1+(g.companion_count||0);let state;if(g.checked_in){state=`<div class="result-already"><b>✓ Entrada já registada</b><span>${g.checked_in_at?new Date(g.checked_in_at).toLocaleString('pt-PT'):''}</span></div>`}else if(g.rsvp_status==='confirmed'){state='<div class="result-valid"><b>✓ Presença confirmada</b><span>Convite válido para a recepção.</span></div>'}else{state=`<div class="result-warning"><b>⚠ Estado: ${esc(g.rsvp_status)}</b><span>Este convidado ainda não confirmou a presença.</span></div>`}box.innerHTML=`<div class="guest-result-inner"><div class="guest-main"><p class="eyebrow">Convidado</p><h2>${esc(g.full_name)}</h2><div class="guest-meta"><span><b>${esc(g.code)}</b></span><span>${people} pessoa(s)</span><span>Permitido: ${g.allowed_guests}</span></div>${state}</div><div class="guest-action">${g.checked_in?'<button class="button secondary" id="again">Próximo convidado</button>':`<button class="button reception-confirm" id="confirm">Confirmar entrada</button>`}</div></div>`;box.classList.remove('hidden');A('#again')?.addEventListener('click',next);A('#confirm')?.addEventListener('click',()=>confirmEntry(g.id));}
async function search(raw){const key=String(raw||'').trim();if(!key){toast('Introduza o código do convite.');A('#code').focus();return}const g=guests.find(x=>x.code.toLowerCase()===key.toLowerCase());if(!g){render(null);toast('Convite não encontrado.');return}render(g)}
async function confirmEntry(id){if(busy)return;const g=guests.find(x=>x.id===id);if(!g||g.checked_in)return;busy=true;const b=A('#confirm');if(b){b.disabled=true;b.textContent='A confirmar…'}const {error}=await supabaseClient.rpc('admin_check_in_invitation',{invitation_id:id});if(error){toast(error.message);busy=false;if(b){b.disabled=false;b.textContent='Confirmar entrada'}return}await loadGuests();toast(`✓ Entrada confirmada — ${g.full_name}`);render(guests.find(x=>x.id===id));setTimeout(next,1800);busy=false}
function next(){A('#result').classList.add('hidden');A('#code').value='';A('#code').focus()}
A('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:A('#email').value,password:A('#password').value});if(error)msg('Email ou palavra-passe incorrectos.');else await enter()};
A('#logout').onclick=()=>supabaseClient.auth.signOut().then(()=>location.reload());A('#search').onclick=()=>search(A('#code').value);A('#code').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search(e.target.value)}});
A('#startScanner').onclick=async()=>{if(!window.Html5Qrcode){toast('Leitor QR indisponível.');return}if(scanner)return;A('#reader').classList.remove('hidden');A('#startScanner').classList.add('hidden');A('#stopScanner').classList.remove('hidden');scanner=new Html5Qrcode('reader');try{await scanner.start({facingMode:'environment'},{fps:12,qrbox:{width:260,height:260}},text=>{let code=text;try{const u=new URL(text);code=u.searchParams.get('convite')||text}catch(_){}A('#code').value=code;search(code);stopScanner()},()=>{})}catch(e){toast('Não foi possível abrir a câmara. Verifique a permissão.');stopScanner()}};
async function stopScanner(){if(scanner){try{await scanner.stop()}catch(_){}try{scanner.clear()}catch(_){}scanner=null}A('#reader').classList.add('hidden');A('#startScanner').classList.remove('hidden');A('#stopScanner').classList.add('hidden')};A('#stopScanner').onclick=stopScanner;
init();
