create table if not exists public.reception_tables (
 id bigint generated by default as identity primary key,
 name text not null unique,
 capacity integer not null check (capacity > 0 and capacity <= 100),
 description text,
 created_at timestamptz not null default now()
);

alter table public.invitations add column if not exists table_id bigint references public.reception_tables(id) on delete set null;

create table if not exists public.protocols (
 id uuid primary key default gen_random_uuid(),
 full_name text not null,
 whatsapp text,
 access_code text not null unique,
 pin_hash text not null,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

alter table public.reception_tables enable row level security;
alter table public.protocols enable row level security;

revoke all on public.reception_tables from anon, authenticated;
revoke all on public.protocols from anon, authenticated;
grant execute on function public.is_admin() to authenticated;

create or replace function public.admin_list_tables()
returns table(id bigint,name text,capacity integer,description text,used_seats bigint,guests jsonb)
language sql security definer set search_path=public
as $$
 select t.id,t.name,t.capacity,t.description,
        count(i.id) filter (where i.rsvp_status='confirmed')::bigint as used_seats,
        coalesce(jsonb_agg(jsonb_build_object('id',i.id,'full_name',i.full_name,'code',i.code,'companion_count',i.companion_count,'rsvp_status',i.rsvp_status) order by i.full_name) filter (where i.id is not null),'[]'::jsonb) as guests
 from reception_tables t left join invitations i on i.table_id=t.id
 where is_admin() group by t.id order by t.name;
$$;

grant execute on function public.admin_list_tables() to authenticated;

create or replace function public.admin_create_table(p_name text,p_capacity integer,p_description text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin if not is_admin() then raise exception 'Não autorizado'; end if;
 insert into reception_tables(name,capacity,description) values(trim(p_name),p_capacity,nullif(trim(p_description),'')) returning id into v_id; return v_id; end $$;
grant execute on function public.admin_create_table(text,integer,text) to authenticated;

create or replace function public.admin_update_table(p_id bigint,p_name text,p_capacity integer,p_description text default null)
returns void language plpgsql security definer set search_path=public as $$
begin if not is_admin() then raise exception 'Não autorizado'; end if; update reception_tables set name=trim(p_name),capacity=p_capacity,description=nullif(trim(p_description),'') where id=p_id; end $$;
grant execute on function public.admin_update_table(bigint,text,integer,text) to authenticated;

create or replace function public.admin_delete_table(p_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin if not is_admin() then raise exception 'Não autorizado'; end if; delete from reception_tables where id=p_id; end $$;
grant execute on function public.admin_delete_table(bigint) to authenticated;

create or replace function public.admin_assign_guest_table(p_invitation_id uuid,p_table_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare cap integer; used integer;
begin if not is_admin() then raise exception 'Não autorizado'; end if;
 if p_table_id is not null then select capacity into cap from reception_tables where id=p_table_id; if cap is null then raise exception 'Mesa não encontrada'; end if;
 select coalesce(sum(1+coalesce(companion_count,0)),0) into used from invitations where table_id=p_table_id and id<>p_invitation_id and rsvp_status='confirmed';
 if used + coalesce((select 1+coalesce(companion_count,0) from invitations where id=p_invitation_id),1) > cap then raise exception 'A mesa não tem lugares suficientes'; end if; end if;
 update invitations set table_id=p_table_id where id=p_invitation_id;
end $$;
grant execute on function public.admin_assign_guest_table(uuid,bigint) to authenticated;

create or replace function public.admin_list_protocols()
returns table(id uuid,full_name text,whatsapp text,access_code text,active boolean,created_at timestamptz)
language sql security definer set search_path=public as $$ select id,full_name,whatsapp,access_code,active,created_at from protocols where is_admin() order by full_name $$;
grant execute on function public.admin_list_protocols() to authenticated;

create extension if not exists pgcrypto;
create or replace function public.admin_create_protocol(p_full_name text,p_whatsapp text,p_access_code text,p_pin text)
returns uuid language plpgsql security definer set search_path=public,extensions as $$ declare v_id uuid; begin if not is_admin() then raise exception 'Não autorizado'; end if; if length(trim(p_pin))<4 then raise exception 'PIN deve ter pelo menos 4 dígitos'; end if; insert into protocols(full_name,whatsapp,access_code,pin_hash) values(trim(p_full_name),nullif(trim(p_whatsapp),''),upper(trim(p_access_code)),crypt(p_pin,gen_salt('bf'))) returning id into v_id; return v_id; end $$;
grant execute on function public.admin_create_protocol(text,text,text,text) to authenticated;

create or replace function public.admin_toggle_protocol(p_id uuid,p_active boolean)
returns void language plpgsql security definer set search_path=public as $$ begin if not is_admin() then raise exception 'Não autorizado'; end if; update protocols set active=p_active where id=p_id; end $$;
grant execute on function public.admin_toggle_protocol(uuid,boolean) to authenticated;

create or replace function public.admin_delete_protocol(p_id uuid)
returns void language plpgsql security definer set search_path=public as $$ begin if not is_admin() then raise exception 'Não autorizado'; end if; delete from protocols where id=p_id; end $$;
grant execute on function public.admin_delete_protocol(uuid) to authenticated;

create or replace function public.verify_protocol(p_access_code text,p_pin text)
returns table(id uuid,full_name text)
language sql security definer set search_path=public,extensions as $$ select id,full_name from protocols where active=true and access_code=upper(trim(p_access_code)) and pin_hash=crypt(p_pin,pin_hash) limit 1 $$;
grant execute on function public.verify_protocol(text,text) to anon,authenticated;

create or replace function public.checkin_protocol_list()
returns table(id uuid,code text,full_name text,whatsapp text,allowed_guests integer,rsvp_status text,companion_count integer,checked_in boolean,checked_in_at timestamptz,table_id bigint,table_name text,table_capacity integer)
language sql security definer set search_path=public as $$
 select i.id,i.code,i.full_name,i.whatsapp,i.allowed_guests,i.rsvp_status,i.companion_count,i.checked_in,i.checked_in_at,i.table_id,t.name,t.capacity
 from invitations i left join reception_tables t on t.id=i.table_id order by i.full_name;
$$;
grant execute on function public.checkin_protocol_list() to anon,authenticated;

create or replace function public.protocol_check_in(p_invitation_id uuid)
returns void language plpgsql security definer set search_path=public as $$ begin update invitations set checked_in=true,checked_in_at=now() where id=p_invitation_id; end $$;
grant execute on function public.protocol_check_in(uuid) to anon,authenticated;

alter table public.protocols add column if not exists session_token uuid;
alter table public.protocols add column if not exists session_expires_at timestamptz;

create or replace function public.verify_protocol(p_access_code text,p_pin text)
returns table(id uuid,full_name text,session_token uuid)
language plpgsql security definer set search_path=public,extensions as $$
declare v_id uuid; v_name text; v_token uuid;
begin
 select p.id,p.full_name into v_id,v_name from protocols p where p.active=true and p.access_code=upper(trim(p_access_code)) and p.pin_hash=crypt(p_pin,p.pin_hash) limit 1;
 if v_id is null then return; end if;
 v_token:=gen_random_uuid(); update protocols set session_token=v_token,session_expires_at=now()+interval '12 hours' where id=v_id;
 return query select v_id,v_name,v_token;
end $$;
grant execute on function public.verify_protocol(text,text) to anon,authenticated;

create or replace function public.protocol_checkin_list(p_token uuid)
returns table(id uuid,code text,full_name text,whatsapp text,allowed_guests integer,rsvp_status text,companion_count integer,checked_in boolean,checked_in_at timestamptz,table_id bigint,table_name text,table_capacity integer)
language sql security definer set search_path=public as $$
 select i.id,i.code,i.full_name,i.whatsapp,i.allowed_guests,i.rsvp_status,i.companion_count,i.checked_in,i.checked_in_at,i.table_id,t.name,t.capacity
 from invitations i left join reception_tables t on t.id=i.table_id
 where exists(select 1 from protocols p where p.session_token=p_token and p.session_expires_at>now() and p.active=true)
 order by i.full_name;
$$;
revoke execute on function public.protocol_checkin_list(uuid) from anon,authenticated;
grant execute on function public.protocol_checkin_list(uuid) to anon,authenticated;

create or replace function public.protocol_check_in(p_token uuid,p_invitation_id uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from protocols p where p.session_token=p_token and p.session_expires_at>now() and p.active=true) then raise exception 'Sessão da recepção expirada'; end if;
 update invitations set checked_in=true,checked_in_at=now() where id=p_invitation_id;
end $$;
grant execute on function public.protocol_check_in(uuid,uuid) to anon,authenticated;

create or replace function public.admin_list_invitations_checkin()
returns table(id uuid,code text,full_name text,whatsapp text,allowed_guests integer,rsvp_status text,companion_count integer,rsvp_note text,rsvp_at timestamptz,invitation_sent_at timestamptz,checked_in boolean,checked_in_at timestamptz,created_at timestamptz,table_id bigint,table_name text,table_capacity integer)
language sql security definer set search_path=public as $$
 select i.id,i.code,i.full_name,i.whatsapp,i.allowed_guests,i.rsvp_status,i.companion_count,i.rsvp_note,i.rsvp_at,i.invitation_sent_at,i.checked_in,i.checked_in_at,i.created_at,i.table_id,t.name,t.capacity
 from invitations i left join reception_tables t on t.id=i.table_id where is_admin() order by i.created_at desc;
$$;
grant execute on function public.admin_list_invitations_checkin() to authenticated;
