-- V6.13 — Protocolo Chefe: gestão autónoma da equipa e tarefas
-- Executar depois das actualizações V6.12.

alter table public.protocols add column if not exists role text not null default 'protocol';
alter table public.protocols drop constraint if exists protocols_role_check;
alter table public.protocols add constraint protocols_role_check check (role in ('protocol','chief'));

create table if not exists public.protocol_tasks(
  id bigint generated by default as identity primary key,
  protocol_id uuid not null references public.protocols(id) on delete cascade,
  title text not null,
  description text,
  completed boolean not null default false,
  created_by uuid references public.protocols(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists protocol_tasks_protocol_id_idx on public.protocol_tasks(protocol_id);
alter table public.protocol_tasks enable row level security;
revoke all on public.protocol_tasks from anon,authenticated;

-- Admin vê o tipo e pode gerir normalmente.
drop function if exists public.admin_list_protocols();
create or replace function public.admin_list_protocols()
returns table(id uuid,full_name text,whatsapp text,access_code text,active boolean,role text,created_at timestamptz)
language sql security definer set search_path=public as $$
 select p.id,p.full_name,p.whatsapp,p.access_code,p.active,p.role,p.created_at
 from public.protocols p where public.is_admin() order by case when p.role='chief' then 0 else 1 end,p.full_name;
$$;
grant execute on function public.admin_list_protocols() to authenticated;

-- Admin pode criar Protocolo ou Protocolo Chefe.
drop function if exists public.admin_create_protocol(text,text,text,text);
create or replace function public.admin_create_protocol(p_full_name text,p_whatsapp text,p_access_code text,p_pin text,p_role text default 'protocol')
returns uuid language plpgsql security definer set search_path=public,extensions as $$
declare v_id uuid; v_role text:=case when lower(trim(coalesce(p_role,'protocol')))='chief' then 'chief' else 'protocol' end;
begin
 if not public.is_admin() then raise exception 'Não autorizado'; end if;
 if length(trim(coalesce(p_full_name,'')))=0 then raise exception 'Nome obrigatório'; end if;
 if length(trim(coalesce(p_access_code,'')))=0 then raise exception 'Código de acesso obrigatório'; end if;
 if length(trim(coalesce(p_pin,'')))<4 then raise exception 'PIN deve ter pelo menos 4 dígitos'; end if;
 if exists(select 1 from public.protocols where upper(access_code)=upper(trim(p_access_code))) then raise exception 'Já existe um protocolo com este código de acesso'; end if;
 insert into public.protocols(full_name,whatsapp,access_code,pin_hash,role)
 values(trim(p_full_name),nullif(trim(p_whatsapp),''),upper(trim(p_access_code)),crypt(trim(p_pin),gen_salt('bf')),v_role)
 returning id into v_id;
 return v_id;
end $$;
grant execute on function public.admin_create_protocol(text,text,text,text,text) to authenticated;

-- A actualização do Admin passa a permitir trocar o tipo.
drop function if exists public.admin_update_protocol(uuid,text,text,text,text);
create or replace function public.admin_update_protocol(p_id uuid,p_full_name text,p_whatsapp text,p_access_code text,p_pin text default null,p_role text default null)
returns void language plpgsql security definer set search_path=public,extensions as $$
declare v_role text;
begin
 if not public.is_admin() then raise exception 'Não autorizado'; end if;
 if length(trim(coalesce(p_full_name,'')))=0 then raise exception 'Nome obrigatório'; end if;
 if length(trim(coalesce(p_access_code,'')))=0 then raise exception 'Código de acesso obrigatório'; end if;
 if length(trim(coalesce(p_pin,''))) > 0 and length(trim(p_pin)) < 4 then raise exception 'PIN deve ter pelo menos 4 dígitos'; end if;
 if p_role is not null then v_role:=case when lower(trim(p_role))='chief' then 'chief' else 'protocol' end; end if;
 if exists(select 1 from public.protocols where upper(access_code)=upper(trim(p_access_code)) and id<>p_id) then raise exception 'Já existe um protocolo com este código de acesso'; end if;
 update public.protocols set full_name=trim(p_full_name),whatsapp=nullif(trim(p_whatsapp),''),access_code=upper(trim(p_access_code)),role=coalesce(v_role,role)
 where id=p_id;
 if not found then raise exception 'Protocolo não encontrado'; end if;
 if length(trim(coalesce(p_pin,'')))>0 then
   update public.protocols set pin_hash=crypt(trim(p_pin),gen_salt('bf')),session_token=null,session_expires_at=null where id=p_id;
 end if;
end $$;
grant execute on function public.admin_update_protocol(uuid,text,text,text,text,text) to authenticated;

-- Login passa a devolver o tipo de acesso.
drop function if exists public.verify_protocol(text,text);
create or replace function public.verify_protocol(p_access_code text,p_pin text)
returns table(id uuid,full_name text,session_token uuid,role text)
language plpgsql security definer set search_path=public,extensions as $$
declare v_id uuid; v_name text; v_role text; v_token uuid;
begin
 select p.id,p.full_name,p.role into v_id,v_name,v_role from public.protocols p
 where p.active=true and upper(trim(p.access_code))=upper(trim(coalesce(p_access_code,''))) and p.pin_hash=crypt(trim(coalesce(p_pin,'')),p.pin_hash) limit 1;
 if v_id is null then return; end if;
 v_token:=gen_random_uuid();
 update public.protocols set session_token=v_token,session_expires_at=now()+interval '12 hours' where id=v_id;
 return query select v_id,v_name,v_token,v_role;
end $$;
grant execute on function public.verify_protocol(text,text) to anon,authenticated;

-- Valida token e papel.
create or replace function public.protocol_identity(p_token uuid)
returns table(id uuid,full_name text,role text)
language sql security definer set search_path=public as $$
 select p.id,p.full_name,p.role from public.protocols p
 where p.active=true and p.session_token=p_token and p.session_expires_at>now();
$$;
grant execute on function public.protocol_identity(uuid) to anon,authenticated;

-- Um Protocolo Chefe pode adicionar novos protocolos, mas não administradores.
create or replace function public.chief_create_protocol(p_token uuid,p_full_name text,p_whatsapp text,p_access_code text,p_pin text)
returns uuid language plpgsql security definer set search_path=public,extensions as $$
declare v_id uuid;
begin
 if not exists(select 1 from public.protocols where id in (select id from public.protocol_identity(p_token)) and role='chief') then raise exception 'Acesso reservado ao Protocolo Chefe'; end if;
 if length(trim(coalesce(p_full_name,'')))=0 then raise exception 'Nome obrigatório'; end if;
 if length(trim(coalesce(p_access_code,'')))=0 then raise exception 'Código de acesso obrigatório'; end if;
 if length(trim(coalesce(p_pin,'')))<4 then raise exception 'PIN deve ter pelo menos 4 dígitos'; end if;
 if exists(select 1 from public.protocols where upper(access_code)=upper(trim(p_access_code))) then raise exception 'Já existe um protocolo com este código de acesso'; end if;
 insert into public.protocols(full_name,whatsapp,access_code,pin_hash,role) values(trim(p_full_name),nullif(trim(p_whatsapp),''),upper(trim(p_access_code)),crypt(trim(p_pin),gen_salt('bf')),'protocol') returning id into v_id;
 return v_id;
end $$;
grant execute on function public.chief_create_protocol(uuid,text,text,text,text) to anon,authenticated;

-- Chefe lista a equipa.
create or replace function public.chief_list_protocols(p_token uuid)
returns table(id uuid,full_name text,whatsapp text,access_code text,active boolean,role text)
language sql security definer set search_path=public as $$
 select p.id,p.full_name,p.whatsapp,p.access_code,p.active,p.role
 from public.protocols p
 where exists(select 1 from public.protocols c where c.id in (select id from public.protocol_identity(p_token)) and c.role='chief')
 order by case when p.role='chief' then 0 else 1 end,p.full_name;
$$;
grant execute on function public.chief_list_protocols(uuid) to anon,authenticated;

-- Chefe cria tarefa para qualquer protocolo (não para outro chefe).
create or replace function public.chief_create_task(p_token uuid,p_protocol_id uuid,p_title text,p_description text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
 if not exists(select 1 from public.protocols c where c.id in (select id from public.protocol_identity(p_token)) and c.role='chief') then raise exception 'Acesso reservado ao Protocolo Chefe'; end if;
 if not exists(select 1 from public.protocols p where p.id=p_protocol_id and p.active=true and p.role='protocol') then raise exception 'Protocolo de destino inválido'; end if;
 if length(trim(coalesce(p_title,'')))=0 then raise exception 'Tarefa obrigatória'; end if;
 insert into public.protocol_tasks(protocol_id,title,description,created_by) select p_protocol_id,trim(p_title),nullif(trim(p_description),''),id from public.protocol_identity(p_token) limit 1 returning id into v_id;
 return v_id;
end $$;
grant execute on function public.chief_create_task(uuid,uuid,text,text) to anon,authenticated;

create or replace function public.chief_list_tasks(p_token uuid)
returns table(id bigint,protocol_id uuid,protocol_name text,title text,description text,completed boolean,created_at timestamptz)
language sql security definer set search_path=public as $$
 select t.id,t.protocol_id,p.full_name,t.title,t.description,t.completed,t.created_at
 from public.protocol_tasks t join public.protocols p on p.id=t.protocol_id
 where exists(select 1 from public.protocols c where c.id in (select id from public.protocol_identity(p_token)) and c.role='chief')
 order by t.completed,t.created_at desc;
$$;
grant execute on function public.chief_list_tasks(uuid) to anon,authenticated;

create or replace function public.chief_toggle_task(p_token uuid,p_task_id bigint,p_completed boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.protocols c where c.id in (select id from public.protocol_identity(p_token)) and c.role='chief') then raise exception 'Acesso reservado ao Protocolo Chefe'; end if;
 update public.protocol_tasks set completed=p_completed,updated_at=now() where id=p_task_id;
end $$;
grant execute on function public.chief_toggle_task(uuid,bigint,boolean) to anon,authenticated;

create or replace function public.chief_delete_task(p_token uuid,p_task_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.protocols c where c.id in (select id from public.protocol_identity(p_token)) and c.role='chief') then raise exception 'Acesso reservado ao Protocolo Chefe'; end if;
 delete from public.protocol_tasks where id=p_task_id;
end $$;
grant execute on function public.chief_delete_task(uuid,bigint) to anon,authenticated;

-- Cada protocolo vê apenas as suas tarefas.
create or replace function public.protocol_my_tasks(p_token uuid)
returns table(id bigint,title text,description text,completed boolean,created_at timestamptz)
language sql security definer set search_path=public as $$
 select t.id,t.title,t.description,t.completed,t.created_at from public.protocol_tasks t
 where t.protocol_id in (select id from public.protocol_identity(p_token)) order by t.completed,t.created_at desc;
$$;
grant execute on function public.protocol_my_tasks(uuid) to anon,authenticated;

create or replace function public.protocol_complete_task(p_token uuid,p_task_id bigint,p_completed boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.protocol_identity(p_token)) then raise exception 'Sessão inválida ou expirada'; end if;
 update public.protocol_tasks set completed=p_completed,updated_at=now() where id=p_task_id and protocol_id in (select id from public.protocol_identity(p_token));
end $$;
grant execute on function public.protocol_complete_task(uuid,bigint,boolean) to anon,authenticated;

notify pgrst, 'reload schema';
